### ISSUE TITLE
error handling with error codes

### ISSUE THREAD

**Issue by rianadutta** [Shared-Reality-Lab/IMAGE-test-graphics#4]
for wrong usage and no output

**Comment by rianadutta** [comment]
I had pushed changes for this issue last week onto testset.py and testdiff.py so it should be good to be closed @jeffbl

**Comment by jeffbl** [comment]
Much improved, since there are error codes for different cases. Thanks! I won't insist, but for future, best practices might include:

1. documenting the errors, or using constants to describe them
2. Having an error exit function so that if the same error can be triggered from multiple places, the string only exists in one place for that error.
3. following standards like POSIX error codes which have existing meanings for some codes (hat tip juliette for [this link](https://www.man7.org/linux/man-pages/man3/errno.3.html).)

I'll leave the priority on these up to you, or if this should be left open / any new issues should be created in current sprints.

**Comment by rianadutta** [comment]
@jeffbl this could be moved into backlog then I think?

**Comment by rianadutta** [comment]
Have created a new issue to address the tasks you addressed above, so I'm closing this.

**Comment by jeffbl** [comment]
For future reference: improvements are broken out into #13
